# Blcok Recognition

## Import Libraries

In [1]:
import numpy as np
import cv2
import glob
from matplotlib import pyplot as plt
import open3d as o3d
import copy
import pickle

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
with open('/home/shs/Desktop/dep.p', 'rb') as dep:
    d = pickle.load(dep, encoding="16UC1")
    
d

array([[403, 404, 404, ..., 797, 797, 797],
       [404, 404, 404, ..., 796, 796, 797],
       [404, 404, 404, ..., 796, 796, 796],
       ...,
       [144, 144, 144, ..., 137, 137, 137],
       [144, 144, 144, ..., 137, 137, 137],
       [144, 144, 144, ..., 137, 137, 137]], dtype=uint16)

In [3]:
with open('/home/shs/Desktop/rgb.p', 'rb') as rgb:
    r = pickle.load(rgb)
    
r

array([[[ 88, 122, 111],
        [103, 137, 126],
        [111, 139, 126],
        ...,
        [175, 175, 159],
        [177, 174, 159],
        [177, 174, 159]],

       [[107, 144, 128],
        [116, 153, 137],
        [121, 150, 134],
        ...,
        [166, 174, 157],
        [166, 174, 157],
        [165, 173, 156]],

       [[110, 148, 130],
        [113, 151, 133],
        [118, 148, 129],
        ...,
        [165, 173, 156],
        [165, 173, 156],
        [165, 173, 156]],

       ...,

       [[182, 210, 187],
        [184, 212, 189],
        [187, 213, 190],
        ...,
        [246, 213, 194],
        [246, 213, 194],
        [246, 213, 194]],

       [[181, 211, 186],
        [183, 213, 188],
        [186, 212, 189],
        ...,
        [245, 212, 193],
        [247, 211, 193],
        [247, 211, 193]],

       [[178, 210, 185],
        [180, 212, 187],
        [184, 212, 189],
        ...,
        [246, 210, 192],
        [248, 210, 192],
        [248, 210, 192]]

In [4]:
d.min()

0

In [5]:
d1 = np.asarray(d, dtype = np.float32)

In [6]:
d2 = d1/915
d2 = np.array(d2, dtype=np.float32)
d2.shape

(1536, 2048)

In [7]:
d3 = np.array(d2 * 255, dtype='uint8')

In [8]:
# cv2.imshow('d2', d3)
# cv2.imwrite('../imgs/depth.png', d3)
# # cv2.imshow('r', r)
# # cv2.imwrite('../imgs/color.png', r)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

## Read Test Images

In [10]:
# img_color = cv2.imread('test_imgs/jenga_tower_color.png')
# img_depth = cv2.imread('test_imgs/jenga_tower_depth.png', 0)
# img_color = cv2.imread('/home/shs/Desktop/rgb1.png')
# img_depth = cv2.imread('/home/shs/Desktop/dep.png', 0)
img_color = r
img_depth = d
print('color shape: ', img_color.shape)
print('depth shape: ', img_depth.shape)

color shape:  (1536, 2048, 3)
depth shape:  (1536, 2048)


## Extract Blocks' Masks By Colors

In [11]:
height, width = img_color.shape[:2] # 이미지의 높이와 너비 불러옴, 가로 [0], 세로[1]

img_hsv = cv2.cvtColor(img_color, cv2.COLOR_BGR2HSV) # cvtColor 함수를 이용하여 hsv 색공간으로 변환

In [12]:
colors = ['green', 'pink', 'yellow', 'blue', 'violet', 'red']

In [13]:
# RED
lower_red1 = np.array([0, 130, 50])
upper_red1 = np.array([15, 255, 255])
lower_red2 = np.array([160,130,50])
upper_red2 = np.array([179,255,255])

# PINK
lower_pink1 = np.array([0, 70, 80])
upper_pink1 = np.array([10, 130, 255])
lower_pink2 = np.array([150,70,80])
upper_pink2 = np.array([179,130,255])

# GREEN
lower_green = (70-20, 50, 50)
upper_green = (70+15, 255, 255)

# YELLOW
lower_yellow = (30-10, 80, 80)
upper_yellow = (30+10, 255, 255)

# BLUE
lower_blue = (100-10, 100, 100)
upper_blue = (100+9, 255, 255)

# VIOLET
lower_violet = (130-20, 60, 60)
upper_violet = (130+20, 255, 255)

In [17]:
blocks_rgb_by_color = []
blocks_mask_by_color = []
for color in colors:
    if color == 'pink' or color =='red':
        for i in (1,2):
            exec(f"lower_color{i} = lower_{color}{i}")
            exec(f"upper_color{i} = upper_{color}{i}")

        mask_color1 = cv2.inRange(img_hsv, lower_color1, upper_color1)
        mask_color2 = cv2.inRange(img_hsv, lower_color2, upper_color2)
        img_mask_color = mask_color1 + mask_color2
        
        # Denoise by Erosion and Dilation
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
        erosion_image_color = cv2.erode(img_mask_color, kernel, iterations=2)  #// make erosion image
        img_mask_color = cv2.dilate(erosion_image_color, kernel, iterations=2)  #// make dilation image

        # 바이너리 이미지를 마스크로 사용하여 원본이미지에서 범위값에 해당하는 영상부분을 획득
        img_result_color = cv2.bitwise_and(img_color, img_color, mask = img_mask_color) 
        
        exec(f"img_result_{color} = img_result_color")
    
    else:
        exec(f"lower_color = lower_{color}")
        exec(f"upper_color = upper_{color}")

        img_mask_color = cv2.inRange(img_hsv, lower_color, upper_color) # 범위내의 픽셀들은 흰색, 나머지 검은색

        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
        erosion_image_color = cv2.erode(img_mask_color, kernel, iterations=2)  #// make erosion image
        img_mask_color = cv2.dilate(erosion_image_color, kernel, iterations=2)  #// make dilation image

        # 바이너리 이미지를 마스크로 사용하여 원본이미지에서 범위값에 해당하는 영상부분을 획득
        img_result_color = cv2.bitwise_and(img_color, img_color, mask = img_mask_color) 

        exec(f"img_result_{color} = img_result_color")
        
    _, src_bin = cv2.threshold(img_mask_color, 0, 255, cv2.THRESH_OTSU)
    each_color_filtered = cv2.bitwise_and(img_color, img_color, mask = src_bin)
    
    # if color == 'red':
    #     cv2.imshow('src_bin', src_bin)
    #     cv2.imwrite('../imgs/red_mask.png', src_bin)
    #     cv2.imshow(f'{color}_filtered', each_color_filtered)
    #     cv2.imwrite('../imgs/red_extract.png', each_color_filtered)
    #     cv2.waitKey(0)
    #     cv2.destroyAllWindows()

    cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

    blocks_color = []
    blocks_mask = []

    for i in range(1, cnt): # 각각의 객체 정보에 들어가기 위해 반복문. 범위를 1부터 시작한 이유는 배경을 제외
        (x, y, w, h, area) = stats[i]
        cen_x, cen_y = map(int, centroids[i])
        block_mask = (labels==i)*img_mask_color
        block_color = cv2.bitwise_and(img_color, img_color, mask = block_mask)
        
        # 노이즈 제거
        if area < 700:
            continue
        
        # if color == 'red' and i==2:
        #     cv2.imshow('blk clr', block_color)
        #     cv2.imwrite('../imgs/red_block2_color.png', block_color)
        #     cv2.imshow('blk msk', block_mask)
        #     cv2.imwrite('../imgs/red_block2_mask.png', block_mask)
        #     cv2.waitKey(0)
        #     cv2.destroyAllWindows()
            
        
        blocks_color.append(block_color)
        blocks_mask.append(block_mask)
        
        
    exec(f"blocks_rgb_{color} = blocks_color")
    exec(f"blocks_mask_{color} = blocks_mask")
    exec(f"blocks_rgb_by_color.append(blocks_rgb_{color})")
    exec(f"blocks_mask_by_color.append(blocks_mask_{color})")
    

In [18]:
tower_mask = 0
tower_color = 0
for mask, color in zip(blocks_mask_by_color, blocks_rgb_by_color):
    for block_m in mask:
        tower_mask += block_m
    
    for block_c in color:
        tower_color += block_c

In [19]:
cv2.imshow('tower mask', tower_mask)
cv2.imwrite('../imgs/tower_mask.png', tower_mask)
cv2.imshow('tower color', tower_color)
cv2.imwrite('../imgs/tower_color.png', tower_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
for c, b, rgb_m in zip(colors, blocks_mask_by_color, blocks_rgb_by_color):
    print(c)
    print(len(b), "Blocks")

green
6 Blocks
pink
6 Blocks
yellow
6 Blocks
blue
6 Blocks
violet
6 Blocks
red
6 Blocks


## Get PointCloud from RGB Image + Depth Image

In [21]:
# temp intrinsic matrix
intrinsic = o3d.camera.PinholeCameraIntrinsic()
intrinsic.intrinsic_matrix = [[968.813, 0, 1023.83],
                              [0, 968.635, 775.975],
                              [0, 0, 1]]


# extrinsic = np.array([[0.999987, 0.00512943, 0.000573447, -32.0559],
#                      [-0.00516119, 0.994725, 0.102443, -1.91788],
#                      [-4.49478e-05, -0.102445, 0.994739, 3.99916],
#                      [0, 0, 0, 1]])
# extrinsic

In [22]:
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=50, origin=[0, 0, 0])
mesh_frame_small = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=0.1, origin=[0, 0, 0])

In [23]:
def get_pointcloud_from_color_depth(color_image, depth_image, intrinsic):
    o3d_img = o3d.geometry.Image()
    
    if isinstance(color_image, type(o3d_img)):
        pass
    elif isinstance(color_image, np.ndarray):
        color_image = cv2.cvtColor(color_image, cv2.COLOR_BGR2RGB)
        color_image = o3d.geometry.Image(color_image)
        
    if isinstance(depth_image, type(o3d_img)):
        pass
    elif isinstance(depth_image, np.ndarray):
        depth_image = o3d.geometry.Image(depth_image)
        
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(color_image, depth_image, depth_scale=1000, convert_rgb_to_intensity=False)
    # print(np.asarray(rgbd_image.depth).max())
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic)
    
    return pcd

In [24]:
masked_depth = cv2.bitwise_and(img_depth, img_depth, mask = tower_mask)

In [25]:
tower_pcd = get_pointcloud_from_color_depth(color_image=tower_color, depth_image=masked_depth, intrinsic=intrinsic)

In [26]:
print(tower_pcd)
print(np.asarray(tower_pcd.points))
o3d.visualization.draw_geometries([tower_pcd])

PointCloud with 269250 points.
[[-0.01771596 -0.07790306  0.215     ]
 [-0.0175754  -0.0782654   0.21600001]
 [-0.01735245 -0.0782654   0.21600001]
 ...
 [-0.01776494  0.10756967  0.23      ]
 [-0.01752753  0.10756967  0.23      ]
 [-0.01729013  0.10756967  0.23      ]]


In [27]:
points = np.asarray(tower_pcd.points)

print("X min/max:", np.min(points[:, 0]), np.max(points[:, 0]))
print("Y min/max:", np.min(points[:, 1]), np.max(points[:, 1]))
print("Z min/max:", np.min(points[:, 2]), np.max(points[:, 2]))

X min/max: -0.19102764527657992 0.05288281771218741
Y min/max: -0.31632264375882324 0.11035418559026333
Z min/max: 0.2150000035762787 0.8889999985694885


In [28]:
blocks_pcd_by_color = []
all_pcd = []
for color, block_mask in zip(colors, blocks_mask_by_color):
    # print(color)
    # if color != 'blue':
    #     continue
    blocks_pcd = []
    for msk in block_mask:
        masked_block_rgb = cv2.bitwise_and(tower_color, tower_color, mask = msk)
        masked_block_depth = cv2.bitwise_and(img_depth, img_depth, mask = msk)
        
        # Get Each Block's PointCloud
        pcd = get_pointcloud_from_color_depth(color_image=masked_block_rgb, depth_image=masked_block_depth, intrinsic=intrinsic)
        
        # Remove Outlier Points
        pcd, _ = pcd.remove_radius_outlier(1024, 0.025)
        blocks_pcd.append(pcd)
        all_pcd.append(pcd)
        
        # if color=='blue':
        #     o3d.visualization.draw_geometries([pcd])
    
    exec(f"blocks_pcd_{color} = blocks_pcd")
    exec(f"blocks_pcd_by_color.append(blocks_pcd_{color})")

In [29]:
len(blocks_pcd_by_color)

6

## Tower ICP

In [30]:
pcd_combined = o3d.geometry.PointCloud()
for point_id in range(len(all_pcd)):
    pcd_combined += all_pcd[point_id]

print(pcd_combined)
# print(len(pcd_combined.points))

PointCloud with 268571 points.


In [31]:
points = np.asarray(pcd_combined.points)

print("X min/max:", np.min(points[:, 0]), np.max(points[:, 0]))
print("Y min/max:", np.min(points[:, 1]), np.max(points[:, 1]))
print("Z min/max:", np.min(points[:, 2]), np.max(points[:, 2]))

X min/max: -0.06122128717399112 0.05288281771218741
Y min/max: -0.08187781871597376 0.11035418559026333
Z min/max: 0.2150000035762787 0.3070000112056732


In [33]:

# o3d.visualization.draw_geometries([pcd_combined, mesh_frame_small])

o3d.visualization.draw_geometries([pcd_combined])

In [34]:
mesh_tower = o3d.io.read_triangle_mesh("mesh/jenga_tower_side_xy.stl")
print(mesh_tower)

mesh_tower.compute_vertex_normals()
# o3d.visualization.draw_geometries([mesh])

pcd_target = mesh_tower.sample_points_uniformly(number_of_points=len(pcd_combined.points))
print(pcd_target)
o3d.visualization.draw_geometries([pcd_target])

TriangleMesh with 12 points and 4 triangles.
PointCloud with 268571 points.


In [35]:
np.linalg.inv(np.asarray([[0, 0, -1, 0],
            [1, 0, 0, 0],
            [0, -1, 0, 0],
            [0, 0, 0, 1]]))

array([[ 0.,  1.,  0.,  0.],
       [-0., -0., -1., -0.],
       [-1., -0., -0., -0.],
       [ 0.,  0.,  0.,  1.]])

In [36]:
initial_transform = np.asarray([[0, 0, -1, 0],
                                [1, 0, 0, 0],
                                [0, -1, 0, 0],
                                [0, 0, 0, 1]])

In [41]:
def prepare_icp(source, target):
    source_tmp = copy.deepcopy(source)
    target_tmp = copy.deepcopy(target)
    
    # make the point cloud into right position
    source_tmp.transform(initial_transform)
    
    # resize the target pointcloud to make two pointclouds into same scale
    resize =(np.array(target_tmp.points)[:,2].max() - np.array(target_tmp.points)[:,2].min()) / (np.array(source_tmp.points)[:,2].max() - np.array(source_tmp.points)[:,2].min())
    
    # move the source pcd to do icp
    move = np.array(target_tmp.get_center() - source_tmp.get_center()*resize)
    
    # a = o3d.cpu.pybind.utility.Vector3dVector(np.array(target_tmp.points))
    b = o3d.cpu.pybind.utility.Vector3dVector(np.array(source_tmp.points)*resize + move)
    
    # target_tmp.points = a
    source_tmp.points = b
    
    o3d.visualization.draw_geometries([source_tmp, target_tmp, mesh_frame])
    
    return source_tmp, target_tmp, resize, move

In [42]:
source, target, resize, move = prepare_icp(pcd_combined, pcd_target)

In [43]:
def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp, mesh_frame])

In [44]:
threshold = 10
trans_init = np.asarray([[1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1]])
draw_registration_result(source, target, trans_init)

In [45]:
print("Initial alignment")
evaluation = o3d.pipelines.registration.evaluate_registration(
    source, target, threshold, trans_init)
print(evaluation)

Initial alignment


RegistrationResult with fitness=5.200673e-01, inlier_rmse=5.637977e+00, and correspondence_set size of 139675
Access transformation to get result.


In [46]:
resize

936.3643857419316

In [47]:
reg_p2p = o3d.pipelines.registration.registration_icp(
    source, target, threshold, trans_init,
    o3d.pipelines.registration.TransformationEstimationPointToPoint(),
    o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=200))
print(reg_p2p)
print("Transformation is:")
print(reg_p2p.transformation)
draw_registration_result(source, target, reg_p2p.transformation)

RegistrationResult with fitness=9.993745e-01, inlier_rmse=2.258697e+00, and correspondence_set size of 268403
Access transformation to get result.
Transformation is:
[[ 5.08964977e-01 -8.60564347e-01 -1.95871793e-02  2.34725724e+01]
 [ 8.60783018e-01  5.08759530e-01  1.47084002e-02 -1.26569343e+00]
 [-2.69236070e-03 -2.43463719e-02  9.99699958e-01  6.55996763e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [48]:
draw_registration_result(source, target, reg_p2p.transformation)

In [49]:
source_temp = copy.deepcopy(source)

source_temp.transform(reg_p2p.transformation)


PointCloud with 268571 points.

In [50]:
(np.array(source_temp.points))[:,2].min()

-1.2091883430174004

In [51]:
resize

936.3643857419316

## Blocks Transformation

In [52]:
trans = reg_p2p.transformation

In [53]:
trans

array([[ 5.08964977e-01, -8.60564347e-01, -1.95871793e-02,
         2.34725724e+01],
       [ 8.60783018e-01,  5.08759530e-01,  1.47084002e-02,
        -1.26569343e+00],
       [-2.69236070e-03, -2.43463719e-02,  9.99699958e-01,
         6.55996763e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [54]:
def transform_blocks(pcd, icp_transform):
    pcd_temp = copy.deepcopy(pcd)
    pcd_temp.transform(initial_transform)
    aa = o3d.cpu.pybind.utility.Vector3dVector(np.array(pcd_temp.points)*resize + move)
    pcd_temp.points = aa
    pcd_temp.transform(icp_transform)
    
    return pcd_temp

In [64]:
# WHAT IS THE TARGET BLOCK?
target_block_color = 'red'
target_block_label = 2

In [66]:
for col, pcds in zip(colors, blocks_pcd_by_color):
    if col != target_block_color:
        continue
    print(col)
    
    for idx, pcd in enumerate(pcds):
        if idx != target_block_label:
            continue
        
        # print("--------------------------------")
        print(idx)
        pcd_new = transform_blocks(pcd, trans)
        
        # o3d.visualization.draw_geometries([pcd_new, mesh_frame, pcd_new.get_axis_aligned_bounding_box()])
        
        box_extent = pcd_new.get_axis_aligned_bounding_box().get_extent()
        print("BOX EXTENT : ", box_extent)
        
        center_coordinate = np.array(pcd_new.get_axis_aligned_bounding_box().get_box_points()).mean(axis=0)
        
        # print(np.array(pcd_new.get_axis_aligned_bounding_box().get_box_points()))
        print("BOX CENTER COORDINATE : ", center_coordinate)
        
        # print("BOX MAX X,Y and MEAN Z Coordinate")
        x_mean = np.array(pcd_new.get_axis_aligned_bounding_box().get_box_points())[:,0].mean()
        y_mean = np.array(pcd_new.get_axis_aligned_bounding_box().get_box_points())[:,1].mean()
        z_mean = np.array(pcd_new.get_axis_aligned_bounding_box().get_box_points())[:,2].mean()
        
        if box_extent[1] > 70:
            print("PULL DIRECTION : X")
            vector = np.array([-1, 0, 0])
            print("-----BLOCK CENTER COORDINATE-----")
            cen_x = x_mean #- 25/2
            cen_y = y_mean #- 75/2
            cen_z = z_mean
            print("X :", cen_x)
            print("Y :", cen_y)
            print("Z :", cen_z)
            pt1 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[cen_x, cen_y, z_mean], [cen_x - 0.01, cen_y - 0.01, cen_z - 0.01], [cen_x + 0.01, cen_y + 0.01, cen_z + 0.01]]))
            print("-----TARGET COORDINATE-----")
            target_x = cen_x + 100
            target_y = cen_y
            target_z = cen_z
            print("X :", target_x)
            print("Y :", target_y)
            print("Z :", target_z)
            pt2 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[target_x, target_y, target_z], [target_x - 0.01, target_y - 0.01, target_z - 0.01], [target_x + 0.01, target_y + 0.01, target_z + 0.01]]))
            print("----------------------------------")
            
        elif box_extent[0] > 70:
            print("PULL DIRECTION : Y")
            vector = np.array([0, -1, 0])
            print("-----BLOCK CENTER COORDINATE-----")
            cen_x = x_mean# - 75/2
            cen_y = y_mean# - 25/2
            cen_z = z_mean
            print("X :", cen_x)
            print("Y :", cen_y)
            print("Z :", cen_z)
            pt1 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[cen_x, cen_y, z_mean], [cen_x - 0.01, cen_y - 0.01, cen_z - 0.01], [cen_x + 0.01, cen_y + 0.01, cen_z + 0.01]]))
            print("-----TARGET COORDINATE-----")
            target_x = cen_x
            target_y = cen_y + 100
            target_z = cen_z
            print("X :", target_x)
            print("Y :", target_y)
            print("Z :", target_z)
            pt2 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[target_x, target_y, target_z], [target_x - 0.01, target_y - 0.01, target_z - 0.01], [target_x + 0.01, target_y + 0.01, target_z + 0.01]]))
            print("----------------------------------")
            
        elif abs(center_coordinate[0]) < 10 and box_extent [1] < 15.1:
            print("PUSH DIRECTION : Y or -Y")
            vector = np.array([0, -1, 0])
            print("-----BLOCK CENTER COORDINATE-----")
            cen_x = x_mean# - 25/2
            cen_y = y_mean - 75/2
            cen_z = z_mean
            print("X :", cen_x)
            print("Y :", cen_y)
            print("Z :", cen_z)
            pt1 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[cen_x, cen_y, z_mean], [cen_x - 0.01, cen_y - 0.01, cen_z - 0.01], [cen_x + 0.01, cen_y + 0.01, cen_z + 0.01]]))
            print("-----TARGET COORDINATE-----")
            target_x = cen_x
            target_y = cen_y + 150
            target_z = cen_z
            print("X :", target_x)
            print("Y :", target_y)
            print("Z :", target_z)
            pt2 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[target_x, target_y, target_z], [target_x - 0.01, target_y - 0.01, target_z - 0.01], [target_x + 0.01, target_y + 0.01, target_z + 0.01]]))
            print("----------------------------------")
            
        elif abs(center_coordinate[1]) < 10 and box_extent [0] < 15.1:
            print("PUSH DIRECTION : X or -X")
            vector = np.array([-1, 0, 0])
            print("-----BLOCK CENTER COORDINATE-----")
            cen_x = x_mean - 75/2
            cen_y = y_mean# - 25/2
            cen_z = z_mean
            print("X :", cen_x)
            print("Y :", cen_y)
            print("Z :", cen_z)
            pt1 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[cen_x, cen_y, z_mean], [cen_x - 0.01, cen_y - 0.01, cen_z - 0.01], [cen_x + 0.01, cen_y + 0.01, cen_z + 0.01]]))
            print("-----TARGET COORDINATE-----")
            target_x = cen_x + 150
            target_y = cen_y
            target_z = cen_z
            print("X :", target_x)
            print("Y :", target_y)
            print("Z :", target_z)
            pt2 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[target_x, target_y, target_z], [target_x - 0.01, target_y - 0.01, target_z - 0.01], [target_x + 0.01, target_y + 0.01, target_z + 0.01]]))
            print("----------------------------------")
            
        elif box_extent[1] < 15.1:
            print("PULL DIRECTION : -X")
            vector = np.array([1, 0, 0])
            print("-----BLOCK CENTER COORDINATE-----")
            cen_x = x_mean# - 25/2
            cen_y = y_mean - 75/2
            cen_z = z_mean
            print("X :", cen_x)
            print("Y :", cen_y)
            print("Z :", cen_z)
            pt1 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[cen_x, cen_y, z_mean], [cen_x - 0.01, cen_y - 0.01, cen_z - 0.01], [cen_x + 0.01, cen_y + 0.01, cen_z + 0.01]]))
            print("-----TARGET COORDINATE-----")
            target_x = cen_x - 100
            target_y = cen_y
            target_z = cen_z
            print("X :", target_x)
            print("Y :", target_y)
            print("Z :", target_z)
            pt2 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[target_x, target_y, target_z], [target_x - 0.01, target_y - 0.01, target_z - 0.01], [target_x + 0.01, target_y + 0.01, target_z + 0.01]]))
            print("----------------------------------")
            
        elif box_extent[0] < 15.1:
            print("PULL DIRECTION : -Y")
            vector = np.array([0, 1, 0])
            print("-----BLOCK CENTER COORDINATE-----")
            cen_x = x_mean - 75/2
            cen_y = y_mean# - 25/2
            cen_z = z_mean
            print("X :", cen_x)
            print("Y :", cen_y)
            print("Z :", cen_z)
            pt1 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[cen_x, cen_y, z_mean], [cen_x - 0.01, cen_y - 0.01, cen_z - 0.01], [cen_x + 0.01, cen_y + 0.01, cen_z + 0.01]]))
            print("-----TARGET COORDINATE-----")
            target_x = cen_x
            target_y = cen_y - 100
            target_z = cen_z
            print("X :", target_x)
            print("Y :", target_y)
            print("Z :", target_z)
            pt2 = o3d.cpu.pybind.utility.Vector3dVector(np.array([[target_x, target_y, target_z], [target_x - 0.01, target_y - 0.01, target_z - 0.01], [target_x + 0.01, target_y + 0.01, target_z + 0.01]]))
            print("----------------------------------")
            
        mesh_COORD = o3d.geometry.TriangleMesh.create_coordinate_frame(size=10, origin=center_coordinate)
        ptc1 = o3d.geometry.PointCloud()
        ptc1.points = pt1
        ptc1.paint_uniform_color([1, 0, 0])
        ptc2 = o3d.geometry.PointCloud()
        ptc2.points = pt2
        ptc2.paint_uniform_color([0, 0, 1])
        line = o3d.geometry.LineSet.create_from_point_cloud_correspondences(ptc1, ptc2, [(0,0)])
        o3d.visualization.draw_geometries([pcd_new, source_temp, mesh_frame, ptc1, ptc2, line])

red
2
BOX EXTENT :  [74.07627068 34.78689947 16.72034444]
BOX CENTER COORDINATE :  [  0.15744993  23.49561882 114.0519394 ]
PULL DIRECTION : Y
-----BLOCK CENTER COORDINATE-----
X : 0.15744993362055126
Y : 23.49561882299917
Z : 114.05193940411306
-----TARGET COORDINATE-----
X : 0.15744993362055126
Y : 123.49561882299918
Z : 114.05193940411306
----------------------------------


In [71]:
o3d.visualization.draw_geometries([source_temp, mesh_frame, source_temp.get_axis_aligned_bounding_box()])

In [72]:
np.array(source_temp.get_axis_aligned_bounding_box().get_box_points())

array([[-37.43618295, -46.40896752,  -1.47427252],
       [ 50.05617671, -46.40896752,  -1.47427252],
       [-37.43618295,  53.85185943,  -1.47427252],
       [-37.43618295, -46.40896752, 178.2339313 ],
       [ 50.05617671,  53.85185943, 178.2339313 ],
       [-37.43618295,  53.85185943, 178.2339313 ],
       [ 50.05617671, -46.40896752, 178.2339313 ],
       [ 50.05617671,  53.85185943,  -1.47427252]])

In [73]:
np.array(source_temp.points)[:,2].max()

178.23393129686926

In [74]:
o3d.visualization.draw_geometries([pcd_new, mesh_frame])

In [119]:
c = np.array([target_x, target_y, target_z, 1])

In [120]:
vector

array([ 0, -1,  0])

In [121]:
c #=np.append(vector, 1)

array([  6.39633969, 133.71786917, 170.82506916,   1.        ])

In [122]:
np.linalg.inv(trans)

array([[ 5.08919930e-01,  8.60809659e-01, -2.68988387e-03,
        -1.09734691e+01],
       [-8.60590949e-01,  5.08714549e-01, -2.43459808e-02,
         2.08631282e+01],
       [-1.95888723e-02,  1.47050445e-02,  9.99699974e-01,
        -2.05791975e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [123]:
np.inner(np.linalg.inv(trans), c)

array([106.9278895 ,  79.22381777, 172.40905534,   1.        ])

In [124]:
c2 = np.inner(np.linalg.inv(trans), c)[:3]

In [125]:
c2

array([106.9278895 ,  79.22381777, 172.40905534])

In [126]:
c3 = c2 - move
c3

array([-149.13279875,   58.02463907,   71.12922451])

In [127]:
c4 = c3 / resize
c4

array([-0.15926769,  0.06196793,  0.07596308])

In [128]:
cc = np.append(c4, 1)
cc

array([-0.15926769,  0.06196793,  0.07596308,  1.        ])

In [129]:
c5 = np.inner(np.linalg.inv(np.asarray([[0, 0, -1, 0],
            [1, 0, 0, 0],
            [0, -1, 0, 0],
            [0, 0, 0, 1]])), cc)[:3]

In [130]:
c5

array([ 0.06196793, -0.07596308,  0.15926769])

In [131]:
resize

936.3656775657781

In [132]:
extrinsic = np.array([[0.999957, 0.00923355, 0.0012111, -32.132],
                      [-0.00930628, 0.995592, 0.0933224, -1.93767],
                      [-0.00034407, -0.0933296, 0.995635, 3.9009],
                      [0,0,0,1]])

In [133]:
ex_inv = np.linalg.inv(extrinsic)
ex_inv

array([[ 9.99956273e-01, -9.30627973e-03, -3.44064524e-04,
         3.21139046e+01],
       [ 9.23355132e-03,  9.95592893e-01, -9.33296850e-02,
         2.58989272e+00],
       [ 1.21110508e-03,  9.33224369e-02,  9.95635408e-01,
        -3.66413085e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [136]:
tar_x, tar_y, tar_z = tuple(c5)

In [142]:
ptpt = o3d.cpu.pybind.utility.Vector3dVector(np.array([[tar_x, tar_y, tar_z], [tar_x - 0.00001, tar_y - 0.00001, tar_z - 0.00001], [tar_x + 0.00001, tar_y + 0.00001, tar_z + 0.00001]]))

In [143]:
ptpt1 = o3d.geometry.PointCloud()
ptpt1.points = ptpt
ptpt1.paint_uniform_color([1, 0, 0])

PointCloud with 3 points.

In [144]:
o3d.visualization.draw_geometries([pcd_combined, ptpt1])

In [134]:
c6 = np.inner(ex_inv, np.append(c5,1))

In [135]:
c6

array([32.17652197,  2.49997219, -3.51257231,  1.        ])