# Blcok Recognition

## Import Libraries

In [1]:
import numpy as np
import cv2
import glob
from matplotlib import pyplot as plt
import open3d as o3d
import copy

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


## Read Test Images

In [2]:
img_color = cv2.imread('test_imgs/jenga_tower_color.png')
img_depth = cv2.imread('test_imgs/jenga_tower_depth.png', 0)
print('color shape: ', img_color.shape)
print('depth shape: ', img_depth.shape)

color shape:  (1536, 2048, 3)
depth shape:  (1536, 2048)


## Extract Blocks' Masks By Colors

In [3]:
height, width = img_color.shape[:2] # 이미지의 높이와 너비 불러옴, 가로 [0], 세로[1]

img_hsv = cv2.cvtColor(img_color, cv2.COLOR_BGR2HSV) # cvtColor 함수를 이용하여 hsv 색공간으로 변환

In [4]:
colors = ['green', 'pink', 'yellow', 'blue', 'violet', 'red']

In [5]:
# RED
lower_red1 = np.array([0, 130, 50])
upper_red1 = np.array([15, 255, 255])
lower_red2 = np.array([160,130,50])
upper_red2 = np.array([179,255,255])

# PINK
lower_pink1 = np.array([0, 70, 80])
upper_pink1 = np.array([10, 130, 255])
lower_pink2 = np.array([150,70,80])
upper_pink2 = np.array([179,130,255])

# GREEN
lower_green = (70-20, 50, 50)
upper_green = (70+15, 255, 255)

# YELLOW
lower_yellow = (30-10, 80, 80)
upper_yellow = (30+10, 255, 255)

# BLUE
lower_blue = (100-10, 100, 100)
upper_blue = (100+9, 255, 255)

# VIOLET
lower_violet = (130-20, 50, 30)
upper_violet = (130+20, 255, 255)

In [6]:
blocks_rgb_by_color = []
blocks_mask_by_color = []
for color in colors:
    if color == 'pink' or color =='red':
        for i in (1,2):
            exec(f"lower_color{i} = lower_{color}{i}")
            exec(f"upper_color{i} = upper_{color}{i}")

        mask_color1 = cv2.inRange(img_hsv, lower_color1, upper_color1)
        mask_color2 = cv2.inRange(img_hsv, lower_color2, upper_color2)
        img_mask_color = mask_color1 + mask_color2
        
        # Denoise by Erosion and Dilation
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
        erosion_image_color = cv2.erode(img_mask_color, kernel, iterations=2)  #// make erosion image
        img_mask_color = cv2.dilate(erosion_image_color, kernel, iterations=2)  #// make dilation image

        # 바이너리 이미지를 마스크로 사용하여 원본이미지에서 범위값에 해당하는 영상부분을 획득
        img_result_color = cv2.bitwise_and(img_color, img_color, mask = img_mask_color) 
        
        exec(f"img_result_{color} = img_result_color")
    
    else:
        exec(f"lower_color = lower_{color}")
        exec(f"upper_color = upper_{color}")

        img_mask_color = cv2.inRange(img_hsv, lower_color, upper_color) # 범위내의 픽셀들은 흰색, 나머지 검은색

        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
        erosion_image_color = cv2.erode(img_mask_color, kernel, iterations=2)  #// make erosion image
        img_mask_color = cv2.dilate(erosion_image_color, kernel, iterations=2)  #// make dilation image

        # 바이너리 이미지를 마스크로 사용하여 원본이미지에서 범위값에 해당하는 영상부분을 획득
        img_result_color = cv2.bitwise_and(img_color, img_color, mask = img_mask_color) 

        exec(f"img_result_{color} = img_result_color")
        
    _, src_bin = cv2.threshold(img_mask_color, 0, 255, cv2.THRESH_OTSU)
    each_color_filtered = cv2.bitwise_and(img_color, img_color, mask = src_bin)
    
    if color == 'blue':
        cv2.imshow('src_bin', src_bin)
        cv2.imshow(f'{color}_filtered', each_color_filtered)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

    cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

    blocks_color = []
    blocks_mask = []

    for i in range(1, cnt): # 각각의 객체 정보에 들어가기 위해 반복문. 범위를 1부터 시작한 이유는 배경을 제외
        (x, y, w, h, area) = stats[i]
        cen_x, cen_y = map(int, centroids[i])
        block_mask = (labels==i)*img_mask_color
        block_color = cv2.bitwise_and(img_color, img_color, mask = block_mask)
        
        # 노이즈 제거
        if area < 600:
            continue
        
        # if color == 'violet':
        #     cv2.imshow('blk clr', block_color)
        #     # cv2.imwrite('./test_imgs/red_block1_rgb.png', block_color)
        #     cv2.imshow('blk msk', block_mask)
        #     # cv2.imwrite('./test_imgs/red_block1_mask.png', block_mask)
        #     cv2.waitKey(0)
        #     cv2.destroyAllWindows()
        
        blocks_color.append(block_color)
        blocks_mask.append(block_mask)
        
        
    exec(f"blocks_rgb_{color} = blocks_color")
    exec(f"blocks_mask_{color} = blocks_mask")
    exec(f"blocks_rgb_by_color.append(blocks_rgb_{color})")
    exec(f"blocks_mask_by_color.append(blocks_mask_{color})")
    

In [7]:
tower_mask = 0
tower_color = 0
for mask, color in zip(blocks_mask_by_color, blocks_rgb_by_color):
    for block_m in mask:
        tower_mask += block_m
    
    for block_c in color:
        tower_color += block_c

In [8]:
cv2.imshow('tower mask', tower_mask)
# cv2.imwrite('./test_imgs/tower_mask.png', tower_mask)
cv2.imshow('tower color', tower_color)
# cv2.imwrite('./test_imgs/tower_color.png', tower_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
for c, b, rgb_m in zip(colors, blocks_mask_by_color, blocks_rgb_by_color):
    print(c)
    print(len(b), "Blocks")

green
6 Blocks
pink
6 Blocks
yellow
6 Blocks
blue
6 Blocks
violet
6 Blocks
red
6 Blocks


## Get PointCloud from RGB Image + Depth Image

In [10]:
# temp intrinsic matrix
intrinsic = o3d.camera.PinholeCameraIntrinsic()
intrinsic.intrinsic_matrix = [[971.179, 0, 1025.07],[0, 970.984, 778.291],[0, 0, 1]]
intrinsic.intrinsic_matrix = [[971.179, 0, 1025.07],[0, 970.984, 778.291],[0, 0, 1]]

In [11]:
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=50, origin=[0, 0, 0])

In [12]:
def get_pointcloud_from_color_depth(color_image, depth_image, intrinsic):
    o3d_img = o3d.geometry.Image()
    
    if isinstance(color_image, type(o3d_img)):
        pass
    elif isinstance(color_image, np.ndarray):
        color_image = cv2.cvtColor(color_image, cv2.COLOR_BGR2RGB)
        color_image = o3d.geometry.Image(color_image)
        
    if isinstance(depth_image, type(o3d_img)):
        pass
    elif isinstance(depth_image, np.ndarray):
        depth_image = o3d.geometry.Image(depth_image)
        
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(color_image, depth_image)
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic)
    
    return pcd

In [13]:
masked_depth = cv2.bitwise_and(img_depth, img_depth, mask = tower_mask)

In [14]:
tower_pcd = get_pointcloud_from_color_depth(color_image=tower_color, depth_image=masked_depth, intrinsic=intrinsic)

In [15]:
print(tower_pcd)
print(np.asarray(tower_pcd.points))
o3d.visualization.draw_geometries([tower_pcd, mesh_frame])

PointCloud with 105303 points.
[[ 3.60051560e-05 -1.69810720e-04  7.45098048e-04]
 [ 3.67723658e-05 -1.69810720e-04  7.45098048e-04]
 [ 3.75395756e-05 -1.69810720e-04  7.45098048e-04]
 ...
 [ 3.50973437e-05  1.22609574e-04  4.54901950e-04]
 [ 3.55657454e-05  1.22609574e-04  4.54901950e-04]
 [ 3.60341472e-05  1.22609574e-04  4.54901950e-04]]


In [16]:
blocks_pcd_by_color = []
all_pcd = []
for color, block_mask in zip(colors, blocks_mask_by_color):
    # print(color)
    blocks_pcd = []
    for msk in block_mask:
        masked_block_rgb = cv2.bitwise_and(tower_color, tower_color, mask = msk)
        masked_block_depth = cv2.bitwise_and(img_depth, img_depth, mask = msk)
        
        # Get Each Block's PointCloud
        pcd = get_pointcloud_from_color_depth(color_image=masked_block_rgb, depth_image=masked_block_depth, intrinsic=intrinsic)
        
        # Remove Outlier Points
        pcd, _ = pcd.remove_radius_outlier(512, 0.0001)
        blocks_pcd.append(pcd)
        all_pcd.append(pcd)
        
        # if color=='green':
        #     o3d.visualization.draw_geometries([pcd])
    
    exec(f"blocks_pcd_{color} = blocks_pcd")
    exec(f"blocks_pcd_by_color.append(blocks_pcd_{color})")

In [17]:
len(blocks_pcd_by_color)

6

## Tower ICP

In [18]:
pcd_combined = o3d.geometry.PointCloud()
for point_id in range(len(all_pcd)):
    pcd_combined += all_pcd[point_id]

print(pcd_combined)
# print(len(pcd_combined.points))

o3d.visualization.draw_geometries([pcd_combined])

PointCloud with 103361 points.


In [19]:
mesh_tower = o3d.io.read_triangle_mesh("mesh/jenga_tower_side_xy.stl")
print(mesh_tower)

mesh_tower.compute_vertex_normals()
# o3d.visualization.draw_geometries([mesh])

pcd_target = mesh_tower.sample_points_uniformly(number_of_points=len(pcd_combined.points))
print(pcd_target)
o3d.visualization.draw_geometries([pcd_target])

TriangleMesh with 12 points and 4 triangles.
PointCloud with 103361 points.


In [20]:
initial_transform = np.asarray([[0, 0, -1, 0],
                        [1, 0, 0, 0],
                        [0, -1, 0, 0],
                        [0, 0, 0, 1]])

In [21]:
def prepare_icp(source, target):
    source_tmp = copy.deepcopy(source)
    target_tmp = copy.deepcopy(target)
    
    # make the point cloud into right position
    source_tmp.transform(initial_transform)
    
    # resize the target pointcloud to make two pointclouds into same scale
    resize = (np.array(target_tmp.points)[:,2].max() - np.array(target_tmp.points)[:,2].min()) / (np.array(source_tmp.points)[:,2].max() - np.array(source_tmp.points)[:,2].min())
    
    # move the source pcd to do icp
    move = np.array(target_tmp.get_center() - source_tmp.get_center()*resize)
    
    # a = o3d.cpu.pybind.utility.Vector3dVector(np.array(target_tmp.points))
    b = o3d.cpu.pybind.utility.Vector3dVector(np.array(source_tmp.points)*resize + move)
    
    # target_tmp.points = a
    source_tmp.points = b
    
    o3d.visualization.draw_geometries([source_tmp, target_tmp, mesh_frame])
    
    return source_tmp, target_tmp, resize, move

In [22]:
source, target, resize, move = prepare_icp(pcd_combined, pcd_target)

In [23]:
def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp])

In [24]:
threshold = 10
trans_init = np.asarray([[1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1]])
draw_registration_result(source, target, trans_init)

In [25]:
print("Initial alignment")
evaluation = o3d.pipelines.registration.evaluate_registration(
    source, target, threshold, trans_init)
print(evaluation)

Initial alignment


RegistrationResult with fitness=5.186095e-01, inlier_rmse=5.215491e+00, and correspondence_set size of 53604
Access transformation to get result.


In [26]:
reg_p2p = o3d.pipelines.registration.registration_icp(
    source, target, threshold, trans_init,
    o3d.pipelines.registration.TransformationEstimationPointToPoint(),
    o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=20000))
print(reg_p2p)
print("Transformation is:")
print(reg_p2p.transformation)
draw_registration_result(source, target, reg_p2p.transformation)

RegistrationResult with fitness=9.988487e-01, inlier_rmse=1.293660e+00, and correspondence_set size of 103242
Access transformation to get result.
Transformation is:
[[ 5.14599677e-01 -8.57126529e-01 -2.28316793e-02  2.44132118e+01]
 [ 8.57422366e-01  5.14295846e-01  1.80739723e-02 -2.05017580e+00]
 [-3.74944333e-03 -2.88772528e-02  9.99575933e-01  7.53390875e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [27]:
draw_registration_result(source, target, reg_p2p.transformation)

In [28]:
source_temp = copy.deepcopy(source)

source_temp.transform(reg_p2p.transformation)


PointCloud with 103361 points.

In [29]:
(np.array(source_temp.points))[:,2].min()

2.6084064314583952

## Blocks Transformation

In [30]:
trans = reg_p2p.transformation

In [31]:
trans

array([[ 5.14599677e-01, -8.57126529e-01, -2.28316793e-02,
         2.44132118e+01],
       [ 8.57422366e-01,  5.14295846e-01,  1.80739723e-02,
        -2.05017580e+00],
       [-3.74944333e-03, -2.88772528e-02,  9.99575933e-01,
         7.53390875e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [32]:
trans_1 = np.asarray([[0, 0, -1, 0],
                         [1, 0, 0, 0],
                         [0, -1, 0, 0],
                         [0, 0, 0, 1]])

In [33]:
def transform_blocks(pcd, icp_transform):
    pcd_temp = copy.deepcopy(pcd)
    pcd_temp.transform(initial_transform)
    aa = o3d.cpu.pybind.utility.Vector3dVector(np.array(pcd_temp.points)*resize + move)
    pcd_temp.points = aa
    pcd_temp.transform(icp_transform)
    
    return pcd_temp

In [34]:
# WHAT IS THE TARGET BLOCK?
target_block_color = 'pink'
target_block_label = 2

In [36]:
for col, pcds in zip(colors, blocks_pcd_by_color):
    # if col != target_block_color:
    #     continue
    print(col)
    
    for idx, pcd in enumerate(pcds):
        if idx != target_block_label:
            continue
        
        print(idx)
        pcd_new = transform_blocks(pcd, trans)
        
        # o3d.visualization.draw_geometries([pcd_new, mesh_frame, pcd_new.get_axis_aligned_bounding_box()])
        
        box_extent = pcd_new.get_axis_aligned_bounding_box().get_extent()
        print("BOX EXTENT : ", box_extent)
        
        center_coordinate = np.array(pcd_new.get_axis_aligned_bounding_box().get_box_points()).mean(axis=0)
        print("CENTER COORDINATE : ", center_coordinate)
        
        if box_extent[1] > 70:
            print("PULL DIRECTION : X")
        elif box_extent[0] > 70:
            print("PULL DIRECTION : Y")
        elif abs(center_coordinate[0]) < 5 and box_extent [1] < 20:
            print("PUSH DIRECTION : Y or -Y")
        elif abs(center_coordinate[1]) < 5 and box_extent [0] < 20:
            print("PUSH DIRECTION : X or -X")
        elif box_extent[1] < 20:
            print("PULL DIRECTION : -X")
        elif box_extent[0] < 20:
            print("PULL DIRECTION : -Y")
            
        mesh_COORD = o3d.geometry.TriangleMesh.create_coordinate_frame(size=10, origin=center_coordinate)
        o3d.visualization.draw_geometries([pcd_new, mesh_frame, pcd_new.get_axis_aligned_bounding_box(), mesh_COORD])

green
2
BOX EXTENT :  [25.71412329 88.13070978 14.85554158]
CENTER COORDINATE :  [25.87202735 -5.75834294 98.07745214]
PULL DIRECTION : X
pink
2
BOX EXTENT :  [25.31985066  4.93170959 13.26101217]
CENTER COORDINATE :  [ 1.64897462 36.64357858 97.54330443]
PUSH DIRECTION : Y or -Y
yellow
2
BOX EXTENT :  [27.70837354  7.08245194 14.00552154]
CENTER COORDINATE :  [-25.65377721  35.9515512   98.0708645 ]
PULL DIRECTION : -X
blue
2
BOX EXTENT :  [83.49992707 26.77117393 14.91361311]
CENTER COORDINATE :  [ -1.60414086  27.31596676 112.44893136]
PULL DIRECTION : Y
violet
2
BOX EXTENT :  [ 3.67253198 27.2791077  14.77310889]
CENTER COORDINATE :  [ 38.28255226   2.92005099 112.88914871]
PUSH DIRECTION : X or -X
red
2
BOX EXTENT :  [ 9.91124081 36.65339815 14.71306576]
CENTER COORDINATE :  [ 34.01654886 -29.01322649 113.02379023]
PULL DIRECTION : -Y
