In [1]:
import open3d as o3d
import numpy as np
import cv2
import glob
from matplotlib import pyplot as plt

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
img_color = cv2.imread('test_imgs/color_align.png')
img_depth = cv2.imread('test_imgs/depth_align.png', 0)
print('color shape: ', img_color.shape)
print('depth shape: ', img_depth.shape)

color shape:  (480, 640, 3)
depth shape:  (480, 640)


In [3]:
intrinsic = o3d.camera.PinholeCameraIntrinsic()
intrinsic.intrinsic_matrix = [[322.282420, 0, 320.818268],[0, 322.282420, 178.779297],[0, 0, 1]]

In [4]:
def get_pointcloud_from_color_depth(color_image, depth_image, intrinsic):
    o3d_img = o3d.geometry.Image()
    
    if isinstance(color_image, type(o3d_img)):
        pass
    elif isinstance(color_image, np.ndarray):
        color_image = cv2.cvtColor(color_image, cv2.COLOR_BGR2RGB)
        color_image = o3d.geometry.Image(color_image)
        
    if isinstance(depth_image, type(o3d_img)):
        pass
    elif isinstance(depth_image, np.ndarray):
        depth_image = o3d.geometry.Image(depth_image)
        
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(color_image, depth_image)
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic)
    
    return pcd

In [5]:
pcd = get_pointcloud_from_color_depth(color_image=img_color, depth_image=img_depth, intrinsic=intrinsic)

In [6]:
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 255829 points.
[[-0.00099546 -0.00055473  0.001     ]
 [-0.00099235 -0.00055473  0.001     ]
 [-0.00098925 -0.00055473  0.001     ]
 ...
 [ 0.00026162  0.00024841  0.00026667]
 [ 0.00026245  0.00024841  0.00026667]
 [ 0.00026327  0.00024841  0.00026667]]


In [7]:
mesh = o3d.io.read_triangle_mesh("test_imgs/jenga_tower.stl")
print(mesh)

TriangleMesh with 36 points and 12 triangles.


In [8]:
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])

In [11]:
pcd = mesh.sample_points_uniformly(number_of_points=5000)
o3d.visualization.draw_geometries([pcd])