In [ ]:
import open3d as o3d
import numpy as np
import cv2
import glob
from matplotlib import pyplot as plt

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
img_color = cv2.imread('test_imgs/color_align.png')
img_depth = cv2.imread('test_imgs/depth_align.png')
print('color shape: ', img_color.shape)
print('depth shape: ', img_depth.shape)

color shape:  (480, 640, 3)
depth shape:  (480, 640, 3)


In [6]:
color = o3d.geometry.Image(img_color)
depth = o3d.geometry.Image(img_depth)

In [7]:
rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(color, depth)

In [10]:
intrinsic = o3d.camera.PinholeCameraIntrinsic()
intrinsic.intrinsic_matrix = [[322.282420, 0, 320.818268],[0, 322.282420, 178.779297],[0, 0, 1]]

In [11]:
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic)

In [17]:
o3d.visualization.draw_geometries([depth])

In [18]:
o3d.visualization.draw_geometries([rgbd_image])

In [19]:
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 255829 points.
[[-0.00099546 -0.00055473  0.001     ]
 [-0.00099235 -0.00055473  0.001     ]
 [-0.00098925 -0.00055473  0.001     ]
 ...
 [ 0.00026162  0.00024841  0.00026667]
 [ 0.00026245  0.00024841  0.00026667]
 [ 0.00026327  0.00024841  0.00026667]]
